### ISSUE TITLE
Animations are delayed

### ISSUE THREAD

**Issue by dalepgrant** [teamcodeand/zeusproductions.com.au---bedrock#73]
Using Safari, the homepage doesn't fully animate in. Leaves big white spaces.

Edit: not limited to Safari. Happens in Chrome too, not currently tested in others.

**Comment by esigolo79** [comment]
Still the same specially on work page

**Comment by dalepgrant** [comment]
https://www.useloom.com/share/e13e370fe9ec4c61a8ca804df685e698
(excuse the jumpy screencast. Loom is usually really good. It's enough to show the issue though).

What seems to be happening is the animations work really well on initial load, but they fuck up on a page refresh. To 'fix' you have to re-size the window, which I'm guessing forces a redraw of the way points. 

I've tried a simple fix by forcing a `$(window).resize();` on page load but that didn't work.

Above video sent to Elementor support, who have already suggested upping the PHP limit to 128 (done).

Worth noting this doesn't happen on the 'Studio' page, which doesn't contain multiple loops.

**Comment by dalepgrant** [comment]
Found to be a chrome extension conflict, won't fix.
