### ISSUE TITLE
Arrows of toggles need to be a cross

### ISSUE THREAD

**Issue by dalepgrant** [teamcodeand/zeusproductions.com.au---bedrock#82]
Eduardo 26/2/18: the arrows of the toggles needs to to change to a cross when you open each one of them.

@dalepgrant 7/3/18: This isn’t in the original design, we don’t have the designs for the cross. That’s not me being an arse ("isn’t a cross a cross?”) - we got the design for the arrows wrong on our first try. Won’t prevent launch, so this change can be looked at after go-live.

Eduardo 23/3/18: the arrows of the toggles needs to to change to a cross when you open each one of them (same cross as menu bar… just smaller of course).

**Comment by esigolo79** [comment]
Yes, please

**Comment by dalepgrant** [comment]
Done.
