### ISSUE TITLE
Studio page: scroll down arrow missing

### ISSUE THREAD

**Issue by dalepgrant** [teamcodeand/zeusproductions.com.au---bedrock#83]
Eduardo 26/2/18: arrow needs to be applied underneath the heading to scroll down the page like on the homepage and work page.

@dalepgrant 7/3/18: not shown in design. Won't prevent launch, leaving for after go-live

Eduardo 23/3/18: arrow needs to be applied underneath the heading to scroll down the page like on the homepage and work page. (I forgot to place it on the original PSD but it is exactly the same position as homepage)

**Comment by esigolo79** [comment]
We need to keep the pages consistent with the elements... Please add the arrow as I forgot to place it on the PSD
