### ISSUE TITLE
Project titles

### ISSUE THREAD

**Issue by dalepgrant** [teamcodeand/zeusproductions.com.au---bedrock#84]
Eduardo 23/3/18: project titles need to be the same size text as Brooke’s name/position on the studio page for the all project section.

**Comment by dalepgrant** [comment]
I've just checked: these are the same size as shown in the design provided by Eduardo. 
![screen shot 2018-03-23 at 15 46 07](https://user-images.githubusercontent.com/12812394/37811971-5b1c2710-2eb1-11e8-8f3e-eb90d1888b58.png)

**Comment by esigolo79** [comment]
Hi Dale, I know that however seen the size on the screen I think it is too big specially on small/square images...

**Comment by dalepgrant** [comment]
@esigolo79 which size screen are we talking about? The font size changes as the screen gets smaller. I'm assuming the largest it goes, but would be good to clarify

**Comment by dalepgrant** [comment]
I've just assumed you want it the same for all, so marking as done
